id: I61EFFEDF
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-29T13:53:45+00:00'
last_modified: '2022-06-08T01:44:28.340782+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG24356
  title: འཕགས་མཆོག་འཇིག་རྟེན་དབང་ཕྱུག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
  base:
    '3882':
      image_group_id: I1KG24454
      title: ''
      total_pages: 458
      order: 1
      base_file: 3882.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
