id: P004531
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 2021-12-17 11:30:19.516217
source_metadata:
  id: bdr:W1KG24356
  title: འཕགས་མཆོག་འཇིག་རྟེན་དབང་ཕྱུག་གི་བྱུང་བ་བརྗོད་པ།
  author: ''
  volumes:
    bf9fd30b07494f84ab092c03a1b229c6:
      image_group_id: I1KG24454
      title: ''
      volume_number: 1
      total_pages: 458
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessFairUse
  restrictedInChina: true
